---
title: "Data Types"
author: "R package build"
date: '2022-02-21'
slug: data-types
categories: R
tags: []
---

# Data Types

## Cat Lovers
```{r}
library(tidyverse)
url <- 'https://raw.githubusercontent.com/dearbharat/tidyverse/main/cat-lovers.csv'
cat_lovers <- read.csv(url)
```

### Summarize Cat Lovers Data
```{r}
cat_lovers %>%
  summarise(mean_cats = mean(number_of_cats, na.rm = TRUE))
```
```{r}
glimpse(cat_lovers)
```

### Fixing the Bad Data
```{r}
cat_lovers %>%
  mutate(number_of_cats = case_when(
    name == "Ginger Clark" ~ 2,
    name == "Doug Bass"    ~ 3,
    TRUE                   ~ as.numeric(number_of_cats)
    )) %>%
  summarise(mean_cats = mean(number_of_cats))
```

## Data Types - Coercion
```{r}
typeof(1.335)
typeof(7L)
typeof(7)
typeof(1:3)
```

## Data Types - Concatenation
```{r}
c(1, 2, 3)
c("Hello", "World!")
c(c("hi", "hello"), c("bye", "jello"))
```

## Explicit Coercion
Number vs. Character
```{r}
x <- 1:3
typeof(x)
typeof(as.character)
```
Number vs. Logical
```{r}
x <- c(TRUE, FALSE)
typeof(x)
typeof(as.numeric(x))
```
Converting between types
```{r}
c(1, "Hello")
c(FALSE, 3L)
```

### Special Values
```{r}
pi / 0
0 / 0
1/0 - 1/0
1/0 + 1/0
```

## NAs 
NAs are special 
```{r}
x <- c(1, 2, 3, 4, NA)
mean(x)
```
```{r}
mean(x, na.rm = TRUE)
```
```{r}
summary(x)
```
NAs are logical  
R uses NA to represent missing values in its data structures.
```{r}
typeof(NA)
```



