---
title: "Self Study Exercise 1"
author: "R package build"
date: '2022-02-16'
slug: self-study-exercises
categories: R
tags: []
---

#Women of Science
## Calling Libraries from Raw Data
```{r}
library(tidyverse)
url <- 'https://raw.githubusercontent.com/dearbharat/tidyverse/main/professions.csv'
professions <- read_csv(url)
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/dates.csv'
dates <- read_csv(url)
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/works.csv'
works <- read_csv(url)
```
## View All Data
```{r}
glimpse(professions)
glimpse(dates)
glimpse(works)
```
## left_join
```{r}
professions %>%
  left_join(dates)
```
## right_join
```{r}
professions %>%
  right_join(dates)
```
## full_join
```{r}
dates %>%
  full_join(works)
```
inner_join
```{r}
dates %>% 
  inner_join(works)
```
## semi_join
```{r}
dates %>%
  semi_join(works)
```
## anti_join
```{r}
dates %>%
  anti_join(works)
```
## Putting It All Together
```{r}
professions %>%
  left_join(dates) %>%
  left_join(works)
```

# Student Records
## Calling Raw Data
```{r}
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/enrolment.csv'
enrolment <- read_csv(url)
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/survey.csv'
survey <- read_csv(url)
```
## left_join and anti_join
### In Class
```{r}
enrolment %>%
  left_join(survey, by = "id")
```
### Survey Missing
```{r}
enrolment %>%
  anti_join(survey, by = "id")
```

### Dropped
```{r}
survey %>%
  anti_join(enrolment, by = "id")
```

# Grocery Sales
```{r}
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/purchases.csv'
purchases <- read_csv(url)
url <- 'https://raw.githubusercontent.com/angelacalicchio/tidyverse/main/prices.csv'
prices <- read_csv(url)
```
## left_join
### Total Revenue
```{r}
purchases %>% 
  left_join(prices)
```
```{r}
purchases %>% 
  left_join(prices) %>%
  summarise(total_revenue = sum(price))
```
### Revenue per Customer
```{r}
purchases %>% 
  left_join(prices)
```
```{r}
purchases %>% 
  left_join(prices) %>%
  group_by(customer_id) %>%
  summarise(total_revenue = sum(price))
```

