---
title: 'A02: Professor Proposes'
author: "R package build"
date: '2022-04-03'
slug: a02-professor-proposes
categories: []
tags: []
---



<div id="link-to-excel-and-csv-files-from-github" class="section level2">
<h2>Link to Excel and CSV Files from GitHub</h2>
<pre class="r"><code>link &lt;- url(&quot;https://github.com/angelacalicchio/a02-diamonds&quot;)</code></pre>
</div>
<div id="loading-data-and-libraries" class="section level1">
<h1>Loading Data and Libraries</h1>
<pre class="r"><code>library(pacman)
library(magrittr)
library(productplots) 
library(psych) 
library(RColorBrewer)
library(tidyverse) </code></pre>
<pre><code>## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──</code></pre>
<pre><code>## ✓ ggplot2 3.3.5     ✓ purrr   0.3.4
## ✓ tibble  3.1.6     ✓ dplyr   1.0.8
## ✓ tidyr   1.2.0     ✓ stringr 1.4.0
## ✓ readr   2.1.2     ✓ forcats 0.5.1</code></pre>
<pre><code>## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## x ggplot2::%+%()     masks psych::%+%()
## x ggplot2::alpha()   masks psych::alpha()
## x tidyr::extract()   masks magrittr::extract()
## x dplyr::filter()    masks stats::filter()
## x dplyr::lag()       masks stats::lag()
## x purrr::set_names() masks magrittr::set_names()</code></pre>
<pre class="r"><code>library(dplyr)

url &lt;- &#39;https://raw.githubusercontent.com/angelacalicchio/a02-diamonds/main/Professor_Proposes_Data.csv&#39;
diamond_selection &lt;- read_csv(url)</code></pre>
<pre><code>## Rows: 441 Columns: 9</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (7): Colour, Clarity, Cut, Certification, Polish, Symmetry, Price
## dbl (2): Carat, Wholesaler
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<pre class="r"><code>View(diamond_selection)</code></pre>
</div>
<div id="eda-exploratory-data-analysis" class="section level1">
<h1>EDA: Exploratory Data Analysis</h1>
<p>While doing an EDA we will be encountering both univariate analysis and multivariate analysis</p>
<div id="creating-a-dataframe-for-data" class="section level3">
<h3>Creating a Dataframe for Data</h3>
<p>We also have to remove the dollar sign and comma so that the data can be explored as a numeric variable</p>
<pre class="r"><code>diamond_selection$Price &lt;- gsub(&quot;,&quot;, &quot;&quot;, diamond_selection$Price)

diamond_selection$Price &lt;- gsub(&quot;\\$&quot;, &quot;&quot;, diamond_selection$Price)

diamond_selection &lt;- na.omit(diamond_selection)

print(diamond_selection)</code></pre>
<pre><code>## # A tibble: 440 × 9
##    Carat Colour Clarity Cut   Certification Polish Symmetry Price Wholesaler
##    &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt;         &lt;chr&gt;  &lt;chr&gt;    &lt;chr&gt;      &lt;dbl&gt;
##  1  0.92 I      SI2     G     AGS           V      V        3000           1
##  2  0.92 I      SI2     V     AGS           G      G        3000           1
##  3  0.82 F      SI2     I     GIA           X      X        3004           1
##  4  0.81 G      SI1     I     GIA           X      V        3004           1
##  5  0.9  J      VS2     V     GIA           V      V        3006           1
##  6  0.87 F      SI2     I     AGS           G      V        3007           1
##  7  0.8  D      SI2     I     GIA           V      V        3008           1
##  8  0.84 F      SI1     G     GIA           V      V        3010           1
##  9  0.8  D      SI2     V     GIA           V      V        3012           1
## 10  0.8  D      SI2     V     GIA           V      X        3012           1
## # … with 430 more rows</code></pre>
<pre class="r"><code>str(diamond_selection)</code></pre>
<pre><code>## tibble [440 × 9] (S3: tbl_df/tbl/data.frame)
##  $ Carat        : num [1:440] 0.92 0.92 0.82 0.81 0.9 0.87 0.8 0.84 0.8 0.8 ...
##  $ Colour       : chr [1:440] &quot;I&quot; &quot;I&quot; &quot;F&quot; &quot;G&quot; ...
##  $ Clarity      : chr [1:440] &quot;SI2&quot; &quot;SI2&quot; &quot;SI2&quot; &quot;SI1&quot; ...
##  $ Cut          : chr [1:440] &quot;G&quot; &quot;V&quot; &quot;I&quot; &quot;I&quot; ...
##  $ Certification: chr [1:440] &quot;AGS&quot; &quot;AGS&quot; &quot;GIA&quot; &quot;GIA&quot; ...
##  $ Polish       : chr [1:440] &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;X&quot; ...
##  $ Symmetry     : chr [1:440] &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;V&quot; ...
##  $ Price        : chr [1:440] &quot;3000&quot; &quot;3000&quot; &quot;3004&quot; &quot;3004&quot; ...
##  $ Wholesaler   : num [1:440] 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int 441
##   ..- attr(*, &quot;names&quot;)= chr &quot;441&quot;</code></pre>
</div>
<div id="converting-price-with-as.numeric" class="section level3">
<h3>Converting Price with as.numeric()</h3>
<pre class="r"><code>diamond_selection$Price &lt;- as.numeric(diamond_selection$Price)

str(diamond_selection)</code></pre>
<pre><code>## tibble [440 × 9] (S3: tbl_df/tbl/data.frame)
##  $ Carat        : num [1:440] 0.92 0.92 0.82 0.81 0.9 0.87 0.8 0.84 0.8 0.8 ...
##  $ Colour       : chr [1:440] &quot;I&quot; &quot;I&quot; &quot;F&quot; &quot;G&quot; ...
##  $ Clarity      : chr [1:440] &quot;SI2&quot; &quot;SI2&quot; &quot;SI2&quot; &quot;SI1&quot; ...
##  $ Cut          : chr [1:440] &quot;G&quot; &quot;V&quot; &quot;I&quot; &quot;I&quot; ...
##  $ Certification: chr [1:440] &quot;AGS&quot; &quot;AGS&quot; &quot;GIA&quot; &quot;GIA&quot; ...
##  $ Polish       : chr [1:440] &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;X&quot; ...
##  $ Symmetry     : chr [1:440] &quot;V&quot; &quot;G&quot; &quot;X&quot; &quot;V&quot; ...
##  $ Price        : num [1:440] 3000 3000 3004 3004 3006 ...
##  $ Wholesaler   : num [1:440] 1 1 1 1 1 1 1 1 1 1 ...
##  - attr(*, &quot;na.action&quot;)= &#39;omit&#39; Named int 441
##   ..- attr(*, &quot;names&quot;)= chr &quot;441&quot;</code></pre>
</div>
<div id="univariate-analyses" class="section level2">
<h2>Univariate Analyses</h2>
<div id="price" class="section level3">
<h3>Price</h3>
<div id="summary" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_price &lt;- summary(diamond_selection$Price)

describe(sum_price, fast = TRUE)</code></pre>
<pre><code>##    vars n    mean      sd min  max range     se
## X1    1 6 1787.21 1244.93 160 3145  2985 508.24</code></pre>
<p>Before, it stated that the minimum was 1, which is simply not true. So, I removed the NA in an earlier chunk, as it was causing difficulties in my EDA.</p>
</div>
<div id="plot" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Price)) +
  geom_histogram(binwidth = 100, fill = &quot;#D872FB&quot;) +
  labs(title = &quot;Price of Diamonds&quot;, x = &quot;Price (US $)&quot;, y = &quot;Frequency&quot;) </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>There was a range in price from $160 to $3145 and, as shown on the graph, had bimodal distribution. Bimodal distribution shows that there are two groups of diamond prices, in which the first group was cheaper than $1000, and the other was more than $1500.</p>
</div>
</div>
<div id="carat" class="section level3">
<h3>Carat</h3>
<div id="summary-1" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_carat &lt;- summary(diamond_selection$Carat)

describe(sum_carat, fast = TRUE)</code></pre>
<pre><code>##    vars n mean   sd  min  max range   se
## X1    1 6 0.74 0.53 0.09 1.58  1.49 0.22</code></pre>
</div>
<div id="plot-1" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Carat)) +
  geom_histogram(binwidth = 0.05, fill = &quot;#F8766D&quot;) +
  labs(title = &quot;Carat of Diamonds&quot;, x = &quot;Carat&quot;, y = &quot;Frequency&quot;) </code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>The Carat ranges from 0.09 to 1.58 and, as shown by the graph, had bimodal distribution. Again, the data appears in two separate groups 0.09 to 0.30 carats and 0.80 to 1.58 carats.</p>
</div>
</div>
<div id="clarity" class="section level3">
<h3>Clarity</h3>
<div id="counts" class="section level4">
<h4>Counts</h4>
<pre class="r"><code>diamond_selection %&gt;%
  count(Clarity)</code></pre>
<pre><code>## # A tibble: 9 × 2
##   Clarity     n
##   &lt;chr&gt;   &lt;int&gt;
## 1 I1         82
## 2 I2         28
## 3 SI1       116
## 4 SI2       110
## 5 SI3        26
## 6 VS1        30
## 7 VS2        41
## 8 VVS1        2
## 9 VVS2        5</code></pre>
</div>
<div id="plot-2" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Clarity)) +
  geom_bar(fill = &quot;#619CFF&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>This graph is self-explanatory. It simply shows the frequencies of each Clarity variable. From the graph, we can see the lowest occurrence variables in this data set are VVS1 and VVS2, which 2 and 5 diamonds, respectively. While the highest frequencies include both SI1 and SI2, with 116 and 110 diamonds, respectively.</p>
</div>
</div>
<div id="color" class="section level3">
<h3>Color</h3>
<div id="summary-2" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_colours &lt;- diamond_selection %&gt;%
  count(Colour)

sum_colours</code></pre>
<pre><code>## # A tibble: 9 × 2
##   Colour     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 D         20
## 2 E         54
## 3 F         58
## 4 G         43
## 5 H         71
## 6 I         79
## 7 J         72
## 8 K         31
## 9 L         12</code></pre>
<p>Using the data we have, we can combine the color codes into their respective color types</p>
<p>Our values should fall into these categories with D -F as Colorless, G - I as Near Colorless, J - K as Faint Yellow, and L as Very light yellow.</p>
<pre class="r"><code>colors &lt;- c(&quot;Colorless&quot;, &quot;Near Colorless&quot;, &quot;Faint Yellow&quot;, &quot;Very Light Yellow&quot;)
numbers &lt;- c(&quot;132&quot;, &quot;193&quot;, &quot;103&quot;, &quot;12&quot;)

color_table &lt;- data.frame(colors, numbers)

glimpse(color_table)</code></pre>
<pre><code>## Rows: 4
## Columns: 2
## $ colors  &lt;chr&gt; &quot;Colorless&quot;, &quot;Near Colorless&quot;, &quot;Faint Yellow&quot;, &quot;Very Light Yel…
## $ numbers &lt;chr&gt; &quot;132&quot;, &quot;193&quot;, &quot;103&quot;, &quot;12&quot;</code></pre>
</div>
<div id="plot-3" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Colour)) +
  geom_bar(fill = &quot;seagreen3&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>As seen by all color data, we have the least number of “Very Light Yellow,” with only 12 diamonds, and the most “Near Colorless,” with 193 diamonds.</p>
</div>
</div>
<div id="cut" class="section level3">
<h3>Cut</h3>
<div id="summary-3" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_cuts &lt;- diamond_selection %&gt;%
  count(Cut)

sum_cuts</code></pre>
<pre><code>## # A tibble: 5 × 2
##   Cut       n
##   &lt;chr&gt; &lt;int&gt;
## 1 F        59
## 2 G        49
## 3 I        86
## 4 V        97
## 5 X       149</code></pre>
<p>Keeping in mind of the Cut Code. F is “Fair,” G is “Good,” I is “Very Good,” V is “Excellent,” and X is “Ideal.”</p>
</div>
<div id="plot-4" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Cut)) +
  geom_bar(fill = &quot;palevioletred1&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Unsurprisingly, most of the diamonds fall into the “Ideal” cut and, while slightly surprising, the “Good” Cut is the least.</p>
</div>
</div>
<div id="certification" class="section level3">
<h3>Certification</h3>
<div id="summary-4" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_certifications &lt;- diamond_selection %&gt;%
  count(Certification)

sum_certifications </code></pre>
<pre><code>## # A tibble: 5 × 2
##   Certification     n
##   &lt;chr&gt;         &lt;int&gt;
## 1 AGS              12
## 2 DOW               1
## 3 EGL             119
## 4 GIA             265
## 5 IGI              43</code></pre>
</div>
<div id="plot-5" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Certification)) +
  geom_bar(fill = &quot;orange2&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>The most certifications seem to GIA, while the least was AGS. Absolutely none of the diamonds have DOW certifications.</p>
</div>
</div>
<div id="polish" class="section level3">
<h3>Polish</h3>
<div id="summary-5" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_polish &lt;- diamond_selection %&gt;%
  count(Polish)

sum_polish </code></pre>
<pre><code>## # A tibble: 6 × 2
##   Polish     n
##   &lt;chr&gt;  &lt;int&gt;
## 1 F          5
## 2 G        165
## 3 I          5
## 4 v          1
## 5 V        203
## 6 X         61</code></pre>
<p>Again the Polish code follows that of the cut code. F is “Fair,” G is “Good,” I is “Very Good,” V is “Excellent,” and X is “Ideal.”</p>
</div>
<div id="plot-6" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Polish)) +
  geom_bar(fill = &quot;purple2&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>Most diamonds are of “Excellent” polished with 203 diamonds. The least is a tie between “Fair” and “Very Good,” with 5 diamonds each. There seems to be a discrepancy with V, as there seems to be a lower case “v” somewhere within the data.</p>
</div>
</div>
<div id="symmetry" class="section level3">
<h3>Symmetry</h3>
<div id="summary-6" class="section level4">
<h4>Summary</h4>
<pre class="r"><code>sum_symmetry &lt;- diamond_selection %&gt;%
  count(Symmetry)

sum_symmetry</code></pre>
<pre><code>## # A tibble: 5 × 2
##   Symmetry     n
##   &lt;chr&gt;    &lt;int&gt;
## 1 F           21
## 2 G          157
## 3 I            5
## 4 V          206
## 5 X           51</code></pre>
<p>Again, the code is the same. F is “Fair,” G is “Good,” I is “Very Good,” V is “Excellent,” and X is “Ideal.”</p>
</div>
<div id="plot-7" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>ggplot(diamond_selection, aes(x = Symmetry)) +
  geom_bar(fill = &quot;gold&quot;)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Most diamonds are of “Excellent” symmetry with 206 diamonds falling under this category. The least amount of diamonds fall under “Very Good” symmetry with 5 diamonds.</p>
</div>
</div>
</div>
<div id="bivariate-analysis" class="section level2">
<h2>Bivariate Analysis</h2>
<div id="price-vs.-carat" class="section level3">
<h3>Price vs. Carat</h3>
<div id="plot-8" class="section level4">
<h4>Plot</h4>
<pre class="r"><code>plot(Price~Carat, diamond_selection)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>We observe that, once again, there are two distinct groups. One of which contain diamonds of lower value and carat, whilst the other contains high value and carat diamonds. We can focus more on those of higher value.</p>
</div>
</div>
</div>
<div id="regression-with-carat" class="section level2">
<h2>Regression with Carat</h2>
<div id="correlation" class="section level3">
<h3>Correlation</h3>
<pre class="r"><code>cor(diamond_selection$Price, diamond_selection$Carat)</code></pre>
<pre><code>## [1] 0.925436</code></pre>
<p>This shows a positive correlation between price and carat</p>
</div>
<div id="model" class="section level3">
<h3>Model</h3>
<pre class="r"><code>model &lt;- lm(diamond_selection$Price ~ diamond_selection$Carat)

summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Carat)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1705.8  -165.9  -111.9   135.2   994.7 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              -200.48      43.11   -4.65  4.4e-06 ***
## diamond_selection$Carat  2864.73      56.04   51.12  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 446 on 438 degrees of freedom
## Multiple R-squared:  0.8564, Adjusted R-squared:  0.8561 
## F-statistic:  2613 on 1 and 438 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>model$coefficients</code></pre>
<pre><code>##             (Intercept) diamond_selection$Carat 
##               -200.4836               2864.7325</code></pre>
<pre class="r"><code>anova(model)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                          Df    Sum Sq   Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Carat   1 519687583 519687583  2612.8 &lt; 2.2e-16 ***
## Residuals               438  87117938    198899                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to the data we’ve collected, r-squared indicates an 85% correlation between carats and price. The negative regression coefficient may represent a carrying capacity of sorts. Meaning heavier diamonds are not always associated with a higher value.</p>
</div>
</div>
<div id="regression-with-clarity" class="section level2">
<h2>Regression with Clarity</h2>
<div id="model-1" class="section level3">
<h3>Model</h3>
<pre class="r"><code>model.2 &lt;- lm(diamond_selection$Price ~ diamond_selection$Clarity)

summary(model.2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Clarity)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2171.2  -571.6  -290.3   582.1  2204.8 
## 
## Coefficients:
##                               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                    2543.15     107.95  23.558  &lt; 2e-16 ***
## diamond_selection$ClarityI2    -201.22     213.97  -0.940  0.34754    
## diamond_selection$ClaritySI1  -1495.53     141.04 -10.604  &lt; 2e-16 ***
## diamond_selection$ClaritySI2   -568.95     142.62  -3.989 7.79e-05 ***
## diamond_selection$ClaritySI3     76.24     220.02   0.347  0.72913    
## diamond_selection$ClarityVS1  -1405.38     208.58  -6.738 5.17e-11 ***
## diamond_selection$ClarityVS2  -1654.95     186.98  -8.851  &lt; 2e-16 ***
## diamond_selection$ClarityVVS1 -1996.15     699.61  -2.853  0.00454 ** 
## diamond_selection$ClarityVVS2 -1978.95     450.31  -4.395 1.40e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 977.6 on 431 degrees of freedom
## Multiple R-squared:  0.3213, Adjusted R-squared:  0.3087 
## F-statistic:  25.5 on 8 and 431 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>model.2$coefficients</code></pre>
<pre><code>##                   (Intercept)   diamond_selection$ClarityI2 
##                    2543.14634                    -201.21777 
##  diamond_selection$ClaritySI1  diamond_selection$ClaritySI2 
##                   -1495.53427                    -568.94634 
##  diamond_selection$ClaritySI3  diamond_selection$ClarityVS1 
##                      76.23827                   -1405.37967 
##  diamond_selection$ClarityVS2 diamond_selection$ClarityVVS1 
##                   -1654.95122                   -1996.14634 
## diamond_selection$ClarityVVS2 
##                   -1978.94634</code></pre>
<pre class="r"><code>anova(model.2)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                            Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Clarity   8 194938677 24367335  25.499 &lt; 2.2e-16 ***
## Residuals                 431 411866844   955608                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to the data that we’ve collected for clarity, the R squared value of 32.13% shows a Positive correlation between price and clarity. Depending on the type of clarity, it may change the price of the diamond. However, some clarity is may reduce the price while others may increase it.</p>
</div>
</div>
<div id="regression-with-certification" class="section level2">
<h2>Regression with Certification</h2>
<pre class="r"><code>model.3 &lt;- lm(diamond_selection$Price ~ diamond_selection$Certification)

summary(model.3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Certification)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1087.82  -912.82   -85.56   461.42  1681.18 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                          3033.4      265.5  11.426  &lt; 2e-16 ***
## diamond_selection$CertificationDOW  -1002.4      957.2  -1.047    0.296    
## diamond_selection$CertificationEGL   -355.6      278.6  -1.277    0.202    
## diamond_selection$CertificationGIA  -1573.6      271.4  -5.797  1.3e-08 ***
## diamond_selection$CertificationIGI  -2767.9      300.3  -9.218  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 919.7 on 435 degrees of freedom
## Multiple R-squared:  0.3937, Adjusted R-squared:  0.3881 
## F-statistic:  70.6 on 4 and 435 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>anova(model.3)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                                  Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Certification   4 238869617 59717404  70.602 &lt; 2.2e-16 ***
## Residuals                       435 367935903   845830                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Again, with a R Square value of 39.37%, we can confidently say that there is a positive correlation between certification and price.</p>
</div>
<div id="regression-with-cut" class="section level2">
<h2>Regression with Cut</h2>
<pre class="r"><code>model.4 &lt;- lm(diamond_selection$Price ~ diamond_selection$Cut)

summary(model.4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Cut)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1987.22 -1111.01   -83.62  1034.23  1912.90 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)              2455.2      145.1  16.916  &lt; 2e-16 ***
## diamond_selection$CutG   -409.2      215.5  -1.899 0.058218 .  
## diamond_selection$CutI   -723.5      188.5  -3.839 0.000142 ***
## diamond_selection$CutV  -1277.1      184.1  -6.939 1.44e-11 ***
## diamond_selection$CutX   -797.2      171.5  -4.649 4.43e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1115 on 435 degrees of freedom
## Multiple R-squared:  0.109,  Adjusted R-squared:  0.1008 
## F-statistic: 13.31 on 4 and 435 DF,  p-value: 3.072e-10</code></pre>
<pre class="r"><code>anova(model.4)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                        Df    Sum Sq  Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Cut   4  66164570 16541142  13.309 3.072e-10 ***
## Residuals             435 540640951  1242853                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to our data, there is an R squared value of 10.9%, which is low, but still shows a positive correlation between price and cut. Certain cuts are worth more, what others lose value. This means that cut does have an affect on the price, however, it is quite a small affect.</p>
</div>
<div id="regression-with-polish" class="section level2">
<h2>Regression with Polish</h2>
<pre class="r"><code>model.5 &lt;- lm(diamond_selection$Price ~ diamond_selection$Polish)

summary(model.3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Certification)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1087.82  -912.82   -85.56   461.42  1681.18 
## 
## Coefficients:
##                                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                          3033.4      265.5  11.426  &lt; 2e-16 ***
## diamond_selection$CertificationDOW  -1002.4      957.2  -1.047    0.296    
## diamond_selection$CertificationEGL   -355.6      278.6  -1.277    0.202    
## diamond_selection$CertificationGIA  -1573.6      271.4  -5.797  1.3e-08 ***
## diamond_selection$CertificationIGI  -2767.9      300.3  -9.218  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 919.7 on 435 degrees of freedom
## Multiple R-squared:  0.3937, Adjusted R-squared:  0.3881 
## F-statistic:  70.6 on 4 and 435 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>anova(model.5)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                           Df    Sum Sq Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Polish   5  28574143 5714829  4.2893 0.0008081 ***
## Residuals                434 578231378 1332330                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Polish also shows a positive correlation with an R Square value of 39.37%. This means that, just like certification, polish has a positive correlation meaning it does affect price to a certain extent.</p>
</div>
<div id="regression-with-symmetry" class="section level2">
<h2>Regression with Symmetry</h2>
<pre class="r"><code>model.6 &lt;- lm(diamond_selection$Price ~ diamond_selection$Symmetry)

summary(model.6)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Symmetry)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1734.4  -945.8   115.6  1171.6  1679.5 
## 
## Coefficients:
##                             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                   2432.3      249.6   9.744  &lt; 2e-16 ***
## diamond_selection$SymmetryG   -537.9      265.8  -2.024 0.043613 *  
## diamond_selection$SymmetryI    615.1      569.2   1.081 0.280440    
## diamond_selection$SymmetryV   -966.8      262.0  -3.690 0.000253 ***
## diamond_selection$SymmetryX   -673.0      296.6  -2.269 0.023754 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1144 on 435 degrees of freedom
## Multiple R-squared:  0.06206,    Adjusted R-squared:  0.05343 
## F-statistic: 7.195 on 4 and 435 DF,  p-value: 1.288e-05</code></pre>
<pre class="r"><code>anova(model.6)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                             Df    Sum Sq Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Symmetry   4  37655698 9413925   7.195 1.288e-05 ***
## Residuals                  435 569149823 1308390                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>While symmetry seem to have a positive correlation, the R Square value is only 6.206%. This means that while Symmetry does have a positive correlation, it probably doesn’t contribute to the price of the diamond.</p>
</div>
<div id="regression-with-color" class="section level2">
<h2>Regression with Color</h2>
<pre class="r"><code>model.7 &lt;- lm(diamond_selection$Price ~ diamond_selection$Colour)

summary(model.7)</code></pre>
<pre><code>## 
## Call:
## lm(formula = diamond_selection$Price ~ diamond_selection$Colour)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2126.2 -1015.2   155.2   970.2  1777.2 
## 
## Coefficients:
##                           Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                2316.20     253.78   9.127  &lt; 2e-16 ***
## diamond_selection$ColourE  -764.29     297.09  -2.573 0.010427 *  
## diamond_selection$ColourF  -982.36     294.31  -3.338 0.000917 ***
## diamond_selection$ColourG  -147.73     307.19  -0.481 0.630810    
## diamond_selection$ColourH  -873.92     287.31  -3.042 0.002496 ** 
## diamond_selection$ColourI  -765.88     284.10  -2.696 0.007296 ** 
## diamond_selection$ColourJ  -535.28     286.88  -1.866 0.062733 .  
## diamond_selection$ColourK    42.06     325.51   0.129 0.897256    
## diamond_selection$ColourL    52.30     414.43   0.126 0.899634    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1135 on 431 degrees of freedom
## Multiple R-squared:  0.08507,    Adjusted R-squared:  0.06809 
## F-statistic: 5.009 on 8 and 431 DF,  p-value: 5.873e-06</code></pre>
<pre class="r"><code>anova(model.7)</code></pre>
<pre><code>## Analysis of Variance Table
## 
## Response: diamond_selection$Price
##                           Df    Sum Sq Mean Sq F value    Pr(&gt;F)    
## diamond_selection$Colour   8  51620143 6452518  5.0092 5.873e-06 ***
## Residuals                431 555185378 1288133                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>According to my data, color also has a small R squared value are only 8.507%. What does means is that the color of the diamond probably also doesn’t affect price all that much.</p>
</div>
</div>
<div id="what-did-we-find-out" class="section level1">
<h1>What did we find out?</h1>
<p>Carat is the primary determinant of the price.</p>
<p>This is followed by clarity, certification, and polish.</p>
<p>Cut, symmetry, and color also do you have the least effect on price and probably didn’t contribute all that much when the diamond was quoted.</p>
<p>The price quoted to the professor seem to be on the higher side; however it did not include the cost of retailing the ring itself. So it’s safe to assume that the price, even though on the higher side, it’s still a fair price all things considered.</p>
<p>Since the professor is only going to buy a diamond once, the professor can offer a price of around $2900-$3000.</p>
</div>
