---
title: 'Validation '
author: "R package build"
date: '2022-03-16'
slug: validation
categories: R
tags: []
---

## Setup
```{r}
library(ISLR)
library(boot)
library(tidyverse)
```

## Cross Validation
### Set Seed
To reproduce the sampling for train - test split
```{r}
set.seed(1)
head(Auto)
dim(Auto)
## Create an index to randomly sample 50% records from Auto
train <- sample(392, 196)
```

## Make the variables in Auto dataset as locally accessible objects
```{r}
attach(Auto)
lm.fit <- lm(mpg~horsepower, data = Auto, subset = train)
lm.fit
```
```{r}
mean((mpg - predict(lm.fit, Auto))[-train]^2)
```
```{r}
plot(mpg, horsepower)
```

## Fit a quadratic function
```{r}
lm.fit.poly <- lm(mpg~poly(horsepower,2), data = Auto, subset = train)
lm.fit.poly
```

**As we increase the degree of the polynomial to 2, the error decreases**
```{r}
mean((mpg - predict(lm.fit.poly, Auto))[-train]^2)
```
```{r}
set.seed(10)
train <- sample(392, 196)
lm.fit <- lm(mpg~horsepower, data = Auto, subset = train)
lm.fit
lm.fit.poly <- lm(mpg~poly(horsepower,2), data = Auto, subset = train)
mean((mpg - predict(lm.fit, Auto))[-train]^2)
mean((mpg - predict(lm.fit.poly, Auto))[-train]^2)
```

## LOO CV: Leave One Out Cross Validation 
```{r}
## GLM defaults to lm when passed without any arguments
glm.fit <- glm(mpg~horsepower, data = Auto)
coef(glm.fit)
lm.fit <- lm(mpg~horsepower, data = Auto)
coef(lm.fit)
```
```{r}
cv.err <- cv.glm(Auto, glm.fit)
cv.err$delta
```
```{r}
cv.error <- rep(0, 5)
degree <- 1:5
for (d in degree){
  glm.fit <- glm(mpg~poly(horsepower,d), data = Auto)
  cv.error[d] <- cv.glm(Auto, glm.fit)$delta[1]
}
cv.error
```
```{r}
plot(degree, cv.error, type = "b")
```

## K Fold Cross Validation
```{r}
K = 10
cv.error.10 <- rep(0, 5)
degree <- 1:5
for (d in degree){
  glm.fit <- glm(mpg~poly(horsepower,d), data = Auto)
  cv.error.10[d] <- cv.glm(Auto, glm.fit, K = K)$delta[1]
}
cv.error.10
```
```{r}
plot(degree, cv.error, type = "b")
lines(degree, cv.error.10, type = "b", col = "red")
```

## Bootstrap Validation
```{r}
## Estimation of Accuracy of a Linear Model
boot.fn <- function(data, index){
  return(coef(lm(mpg~horsepower, data = data, subset = index)))
}
```
```{r}
boot.fn(Auto, 1:392)
```
```{r}
set.seed(1)
boot.fn(Auto, sample(392, 392, replace = T))
```
```{r}
boot.out <- boot(Auto, boot.fn, 1000)
```
```{r}
plot(boot.out)
```

